defuse-protocol/defuse-frontend

src/app/swap/page.tsx, src/components/Block/BlockMultiBalances.tsx, src/components/ConnectWallet/index.tsx, src/components/History/Widget/WidgetCard.tsx, src/components/Modal/ModalConfirmSwap.tsx, src/components/Modal/ModalReviewSwap.tsx, src/components/Network/AssetComboIcon.tsx, src/hooks/useConnectWallet.ts, src/hooks/useGetTokensBalance.ts, src/hooks/useHistoryLatest.ts, src/hooks/useSwap.ts, src/types/interfaces.ts, src/utils/token.ts
=> feat/Update use Near with wNear

package.json, yarn.lock
=> fix/Quoting from ref-finance

.env.development, src/app/layout.tsx, src/components/History/Widget/WidgetCard.tsx, src/components/Modal/ModalReviewSwap.tsx, src/hocs/withHistory.tsx, src/hooks/useGetTokensBalance.ts, src/hooks/useHistoryCollector.ts, src/hooks/useHistoryLatest.ts, src/hooks/useSwap.ts, src/libs/de-sdk/utils/adapters.ts, src/libs/de-sdk/utils/intents.ts, src/libs/de-sdk/utils/maps.ts, src/types/interfaces.ts, src/utils/near.ts
- add support native_on_transfer method at WidgetCard
- add intents statuses adapter
=> fix: transaction-notification

src/api/account.ts, src/components/History/Widget/WidgetCard.tsx, src/components/Modal/ModalConfirmSwap.tsx, src/components/Modal/ModalReviewSwap.tsx, src/components/SwapForm/index.tsx, src/components/SwapForm/service/getBalanceNear.ts, src/components/SwapForm/service/getBalanceNearAllowedToSwap.ts, src/constants/contracts.ts, src/hooks/useGetTokensBalance.ts, src/hooks/useMinimumNearBalance.ts, src/hooks/useSwap.ts, src/types/interfaces.ts, src/utils/near.ts
- Calculate maximum available balance to swap
=> fix: swap withdraw

src/components/SwapForm/service/getBalanceNearAllowedToSwap.ts, src/hooks/useGetTokensBalance.ts, src/providers/WalletSelectorProvider.tsx, src/utils/tokenList.ts
Disable unsupported wallets until fixes
=> fix: estimate of wallets with storage per byte less than 740

package.json, yarn.lock
Closes https://app.clickup.com/t/86eqezm0t
=> chore: upgrade defuse sdk

package.json, src/app/layout.tsx, src/app/swap/page.tsx, src/components/Paper.tsx, src/hocs/withTokensBalance.tsx, yarn.lock
- Disable fetching token balances
- Fix Paper children wrapper, moving it to the form itself
- Apply SDK styles
- Add dummy sign message implementation
This PR tests how form styles behave in case of overriding and prepares the frontend app to test sign message functionality.
=> chore: update swap form

package.json, src/app/my-near-wallet-gateway/layout.tsx, src/app/my-near-wallet-gateway/page.tsx, src/app/my-near-wallet-poc/layout.tsx, src/app/my-near-wallet-poc/page.tsx, src/hooks/useNearWalletActions.ts, src/utils/myNearWalletAdapter.test.ts, src/utils/myNearWalletAdapter.ts, vitest.config.ts, yarn.lock
PR is basically a result of my research of whether singing a message using MyNearWallet without leaving a page is possible. 
And yes, it is possible. 
I created a special page "my-near-wallet-gateway" that is responsible for communication between an app and MyNearWallet. When user wants to sign something, we open that page and they don't leave the original page at all. 
I added an implementation to see how may it look like http://localhost:3000/my-near-wallet-poc
=> Sign using MyNearWallet without leaving a page

package.json, src/app/swap/page.tsx, yarn.lock
PR: 
- upgrades Defuse SDK
- updates usage of SwapWidget to support singing and showing a success toast message
=> feat(swap): add swap message singing

package.json, src/app/swap/page.tsx, src/hooks/useNearWalletActions.ts, src/utils/myNearWalletAdapter.ts, yarn.lock
Waiting https://github.com/defuse-protocol/defuse-sdk/pull/52 to be released
=> fix: explicitly set `callbackUrl`

package.json, src/app/withdraw/page.tsx, src/constants/routes.ts, yarn.lock
Waiting https://github.com/defuse-protocol/defuse-sdk/pull/56 to be released
=> chore: update withdraw page

src/components/ComingSoon/index.tsx, src/components/NavbarMobile.tsx, src/components/Settings.tsx, src/components/Wallet/index.tsx
Additional:
- Hide total balance and disable transaction history, with 'coming soon' label
=> fix: mobile navigation

.env.development, .env.production, src/app/layout.tsx, src/components/LabelNew.tsx, src/components/Settings.tsx
Key Changes:
- Add feature flag for Dark Mode
- Add telegram Channel Link
=> feat: add TG channel and update dark mode

src/components/Wallet/index.tsx
=> chore: add agreement dialog for near connection

.env.production, src/components/Wallet/index.tsx
PR changes:
- Delete all wallet button connectors except Solana from the wallet connections menu.
=> feat: enable only solona connection

next.config.mjs
Console warnings:
```
Module not found: Can't resolve 'encoding' in 'defuse-frontend/node_modules/@metamask/sdk/dist/node/es'
Import trace for requested module:
./node_modules/@metamask/sdk/dist/node/es/metamask-sdk.js
./node_modules/@wagmi/connectors/dist/esm/metaMask.js
./node_modules/@wagmi/connectors/dist/esm/exports/index.js
./node_modules/wagmi/dist/esm/exports/connectors.js
./src/config/wagmi.ts
./src/app/layout.tsx
./node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in 'defuse-frontend/node_modules/pino/lib'
Import trace for requested module:
./node_modules/pino/lib/tools.js
./node_modules/pino/pino.js
./node_modules/@walletconnect/logger/dist/index.es.js
./node_modules/@walletconnect/universal-provider/dist/index.es.js …
```
=> Suppress dev warnings

src/components/Paper.tsx
Link specific to `turboswap` only.
=> fix: add link to powered by aurora labs

package.json, src/app/deposit/page.tsx, src/hooks/useEVMWalletActions.ts, yarn.lock
Depends on https://github.com/defuse-protocol/defuse-sdk/pull/186
=> fix: add chain switching before sending transaction

src/components/Wallet/index.tsx
Fixed misalign for ledger confirmation
=> fix: small screen confirmation misaligned

src/utils/myNearWalletAdapter.ts
User facing exceptions since their browser is "old". Safari started to support it only this year.
https://caniuse.com/?search=abortsignal.any
=> fix: add polyfill for AbortSignal.any

src/components/AddTurboChainButton.tsx, src/components/Layout/Header.tsx, src/components/Settings.tsx, src/config/wagmi.ts
<details><summary>Details</summary>
<p>
</p>
</details>
=> feat: add Trubochain button

package.json, src/components/AddTurboChainButton.tsx, src/components/Wallet/index.tsx, src/config/wagmi.ts, src/hooks/useConnectWallet.ts, yarn.lock
<details><summary>Details</summary>
<p>
</p>
</details>
=> fix: fix adding chain; add error and success states

package.json, src/app/layout.tsx, src/components/InitDefuseSDK.tsx, src/libs/defuse-sdk/initSDK.ts, yarn.lock
Requires https://github.com/defuse-protocol/defuse-sdk/pull/215
=> chore: send sdk logs to sentry

.catalog-info.yaml
=> chore: update catalog info

src/app/(home)/page.tsx, src/constants/tokens.ts, src/hooks/useTokenList.ts
<details><summary>Screenshot</summary>
<p>
</p>
</details>
=> feat: reorder tokens according to marketcap

package.json, src/app/account/layout.tsx, src/app/account/page.tsx, src/components/Paper.tsx, src/components/Wallet/WalletConnections.tsx, src/components/Wallet/index.tsx, src/constants/routes.ts, src/stores/useSignInWindowOpenState.ts, src/utils/renderAppLink.tsx, yarn.lock
Needs https://github.com/defuse-protocol/defuse-sdk/pull/342
=> feat: add account page

package.json, src/app/(home)/page.tsx, src/app/deposit/page.tsx, src/app/otc-desk/create-order/page.tsx, src/app/withdraw/page.tsx, src/components/Navbar.tsx, src/components/Paper.tsx, src/constants/routes.ts, src/utils/renderAppLink.tsx, yarn.lock
<details><summary>Details</summary>
<p>
</p>
</details>
=> fix: update widget titles and links

src/components/Layout/Header.tsx, src/components/Layout/index.tsx, src/components/Navbar/NavbarDesktop.tsx, src/components/Navbar/NavbarMobile.tsx
Renamed Navbar to Navbar Desktop for better distinguish between desktop and mobile components.
=> refactor: move navbar to header slot

src/components/Layout/index.tsx, src/components/Logo.tsx, src/components/Navbar/NavbarDesktop.tsx, src/components/Navbar/NavbarMobile.tsx, src/constants/routes.ts, src/hooks/useIsActiveLink.ts, src/utils/cn.ts
<details>
<summary>Screen</summary>
</details>
=> feat: mobile navigation

src/components/Navbar/NavbarDesktop.tsx
Use Link component for desktop navigation. This allows user to use mouse wheel to open page in a new tab.
=> feat: use Link for navigation in desktop
